// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMiDPbEcAbnAp46EXkPoIUAIX4TSffbCI',
    appId: '1:457417881010:web:3e9de11891c097281a60ab',
    messagingSenderId: '457417881010',
    projectId: 'afl-dataset',
    authDomain: 'afl-dataset.firebaseapp.com',
    storageBucket: 'afl-dataset.firebasestorage.app',
    measurementId: 'G-2JZ1P5PWCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZtqbjfUHayWLyO--4WWCOITLlCULwmcI',
    appId: '1:457417881010:android:a629fbbba8aba4a41a60ab',
    messagingSenderId: '457417881010',
    projectId: 'afl-dataset',
    storageBucket: 'afl-dataset.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu_NfXEyWZTfrbNI-n0RB-wVUNWXbKRus',
    appId: '1:457417881010:ios:50420bfa250b86b21a60ab',
    messagingSenderId: '457417881010',
    projectId: 'afl-dataset',
    storageBucket: 'afl-dataset.firebasestorage.app',
    iosBundleId: 'com.example.aflStatsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu_NfXEyWZTfrbNI-n0RB-wVUNWXbKRus',
    appId: '1:457417881010:ios:50420bfa250b86b21a60ab',
    messagingSenderId: '457417881010',
    projectId: 'afl-dataset',
    storageBucket: 'afl-dataset.firebasestorage.app',
    iosBundleId: 'com.example.aflStatsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMiDPbEcAbnAp46EXkPoIUAIX4TSffbCI',
    appId: '1:457417881010:web:7918901e6f7ef6d71a60ab',
    messagingSenderId: '457417881010',
    projectId: 'afl-dataset',
    authDomain: 'afl-dataset.firebaseapp.com',
    storageBucket: 'afl-dataset.firebasestorage.app',
    measurementId: 'G-G8LCDG0V1N',
  );
}
